version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: safe-backend-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: safe-deployment-service
    volumes:
      - mongodb_data:/data/db
    networks:
      - safe-dev

  redis:
    image: redis:7-alpine
    container_name: safe-backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - safe-dev

  # Optional: Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: safe-backend-redis-gui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - safe-dev

  # Optional: MongoDB Express (MongoDB GUI)
  mongo-express:
    image: mongo-express:latest
    container_name: safe-backend-mongo-gui
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/safe-deployment-service
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - safe-dev

volumes:
  mongodb_data:
  redis_data:

networks:
  safe-dev:
    driver: bridge
